CREATE TABLE IF NOT EXISTS users (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  email VARCHAR(120) NOT NULL UNIQUE,
  passwordHash VARCHAR(100) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS images (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  userId BIGINT UNSIGNED NOT NULL,
  filename VARCHAR(255) NOT NULL,
  originalPath VARCHAR(255) NOT NULL,
  thumbPath VARCHAR(255) NOT NULL,
  mime VARCHAR(100),
  width INT,
  height INT,
  exifTakenAt DATETIME NULL,
  exifLat DECIMAL(10,7) NULL,
  exifLng DECIMAL(10,7) NULL,
  resolution VARCHAR(50),
  note VARCHAR(255),
  KEY idx_user (userId),
  KEY idx_takenAt (exifTakenAt),
  CONSTRAINT fk_images_user FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS tags (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(80) NOT NULL UNIQUE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS image_tags (
  imageId BIGINT UNSIGNED NOT NULL,
  tagId BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (imageId, tagId),
  KEY idx_tag (tagId),
  CONSTRAINT fk_it_image FOREIGN KEY (imageId) REFERENCES images(id) ON DELETE CASCADE,
  CONSTRAINT fk_it_tag FOREIGN KEY (tagId) REFERENCES tags(id) ON DELETE CASCADE
) ENGINE=InnoDB;
